version: "3.7"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: vr
      MYSQL_PASSWORD: 123
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
#  app:
#    build: ../
#    container_name: miniautorizador
#    ports:
#      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy